# TCL File Generated by Component Editor 18.1
# Tue Dec 14 05:28:40 CST 2021
# DO NOT MODIFY


# 
# ppu_interace "PPU Interface" v1.0
#  2021.12.14.05:28:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ppu_interace
# 
set_module_property DESCRIPTION ""
set_module_property NAME ppu_interace
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "PPU Interface"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ppu_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ppu_interface.sv SYSTEM_VERILOG PATH ppu_interface.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point avalon_mm_slave_1
# 
add_interface avalon_mm_slave_1 avalon end
set_interface_property avalon_mm_slave_1 addressUnits SYMBOLS
set_interface_property avalon_mm_slave_1 associatedClock CLK
set_interface_property avalon_mm_slave_1 associatedReset RESET
set_interface_property avalon_mm_slave_1 bitsPerSymbol 8
set_interface_property avalon_mm_slave_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_mm_slave_1 burstcountUnits SYMBOLS
set_interface_property avalon_mm_slave_1 explicitAddressSpan 0
set_interface_property avalon_mm_slave_1 holdTime 0
set_interface_property avalon_mm_slave_1 linewrapBursts false
set_interface_property avalon_mm_slave_1 maximumPendingReadTransactions 0
set_interface_property avalon_mm_slave_1 maximumPendingWriteTransactions 0
set_interface_property avalon_mm_slave_1 readLatency 0
set_interface_property avalon_mm_slave_1 readWaitTime 1
set_interface_property avalon_mm_slave_1 setupTime 0
set_interface_property avalon_mm_slave_1 timingUnits Cycles
set_interface_property avalon_mm_slave_1 writeWaitTime 0
set_interface_property avalon_mm_slave_1 ENABLED true
set_interface_property avalon_mm_slave_1 EXPORT_OF ""
set_interface_property avalon_mm_slave_1 PORT_NAME_MAP ""
set_interface_property avalon_mm_slave_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_mm_slave_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_mm_slave_1 AVL_ADDR address Input 16
add_interface_port avalon_mm_slave_1 AVL_CS chipselect Input 1
add_interface_port avalon_mm_slave_1 AVL_READ read Input 1
add_interface_port avalon_mm_slave_1 AVL_WRITE write Input 1
add_interface_port avalon_mm_slave_1 AVL_WRITEDATA writedata Input 8
add_interface_port avalon_mm_slave_1 AVL_READDATA readdata Output 8
set_interface_assignment avalon_mm_slave_1 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_mm_slave_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_mm_slave_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_mm_slave_1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point VGA_port
# 
add_interface VGA_port conduit end
set_interface_property VGA_port associatedClock CLK
set_interface_property VGA_port associatedReset ""
set_interface_property VGA_port ENABLED true
set_interface_property VGA_port EXPORT_OF ""
set_interface_property VGA_port PORT_NAME_MAP ""
set_interface_property VGA_port CMSIS_SVD_VARIABLES ""
set_interface_property VGA_port SVD_ADDRESS_GROUP ""

add_interface_port VGA_port red red Output 4
add_interface_port VGA_port green green Output 4
add_interface_port VGA_port blue blue Output 4
add_interface_port VGA_port hs hs Output 1
add_interface_port VGA_port vs vs Output 1


# 
# connection point CLK_4
# 
add_interface CLK_4 clock end
set_interface_property CLK_4 clockRate 4000000
set_interface_property CLK_4 ENABLED true
set_interface_property CLK_4 EXPORT_OF ""
set_interface_property CLK_4 PORT_NAME_MAP ""
set_interface_property CLK_4 CMSIS_SVD_VARIABLES ""
set_interface_property CLK_4 SVD_ADDRESS_GROUP ""

add_interface_port CLK_4 CLK_4 clk Input 1


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1

